### ISSUE TITLE
Error using gtsam.noiseModel.mEstimator.Huber.Create (line 75)

### ISSUE THREAD

**Issue by Oussamaaat** [taroz/gsdc2023#2]
Matlab output : 

```
Error using gtsam.noiseModel.mEstimator.Huber.Create (line 75) 

Exception from gtsam:
active expects 1 arguments, not 0


Error in parameters (line 83) %
prm.P_kernel = huber(prm.P_robust_prm); % Huber kernel

Error in fgo_gnss_imu (line 35) %
prm = parameters(setting, initflag); % Processing parameter

Error in run_fgo (line 28)
parfor i=1:n

```

Files involved : 

gtsam\build\wrap\gtsam\+gtsam\+noiseModel\+mEstimator\Huber.m
gsdc2023-main\parameters.m
gsdc2023-main\fgo_gnss_imu.m
and run_fgo.m

Thank you !

**Comment by taroz** [comment]
I have replied to [this issue](https://github.com/taroz/gsdc2023/issues/1#issuecomment-2415960945), but please wait a little longer as I am currently preparing a tutorial on building on a Windows environment. 

If you want to test the operation of the MATLAB wrapper for gtsam built on Windows, I think it would be a good idea to use gtsam/matlab/gtsam_test and gtsam/matlab/example to check that it works.

**Comment by Oussamaaat** [comment]
Okay thank you very much Mr Taro !
